
# file: .github/workflows/name-1.yaml

name: name-2

env:
  GLOBAL_ENV_NAME: "global_env_name_${{github.sha}}"

on:
  push:
    branches:
      - master

jobs:
  name-3-1:
    runs-on: ubuntu-latest
    steps:
      - name: name-4-1-1
        run: |
          echo "Hello, ${{env.GLOBAL_ENV_NAME}}, from name-3-1"

      - name: name-4-1-2
        run: |
          echo "Before checkout"
          ls -al

      - name: name-4-1-3
        uses: actions/checkout@v1

      - name: name-4-1-4
        run: |
          echo "After checkout"
          ls -al
  name-3-2:
    runs-on: ubuntu-latest
    needs: [name-3-1]
    steps:
      - name: name-4-2
        run: echo "Hello, ${{env.GLOBAL_ENV_NAME}}, from name-3-2"
